Initial Contribution of the sldt-discovery-finder
eclipse-tractusx/sldt-discovery-finder pull request #1
Opened 2023-03-22 12:17 UTC by tunacicek

* Initial Contribution for sldt-discovery-finder
* Copyright information -> please check the respective notices in the source code.

2023-03-24 13:40 UTC, LuLeRoemer requested changes

2023-03-24 13:40 UTC, LuLeRoemer commented on docs/1-introduction-and-goals.md
What about these files?

2023-03-24 13:40 UTC, LuLeRoemer commented on charts/discoveryfinder/templates/_helpers.tpl
Would not commit empty file.

2023-03-24 13:40 UTC, LuLeRoemer commented on charts/discoveryfinder/LICENSE
What's the extra license file for?

2023-03-27 07:15 UTC, tunacicek commented on docs/1-introduction-and-goals.md
These files were created for preparation for the documentation task (As structure of the documentation)

2023-03-27 08:52 UTC, tunacicek commented on charts/discoveryfinder/templates/_helpers.tpl
Empty file is removed.

2023-03-27 08:52 UTC, tunacicek commented on charts/discoveryfinder/LICENSE
Extra license is removed.

2023-03-28 08:26 UTC, LuLeRoemer approved these changes
LGTM

2023-03-28 11:14 UTC, merged